# Generated by Django 5.1.1 on 2024-10-04 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('unique_id', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('big_metadata', models.JSONField(blank=True, null=True)),
                ('secret_value', models.JSONField(blank=True, null=True)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=1024)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('title', models.TextField(blank=True)),
                ('like_count', models.BigIntegerField(blank=True, default=0)),
                ('comment_count', models.BigIntegerField(blank=True, default=0)),
                ('view_count', models.BigIntegerField(blank=True, default=0)),
                ('share_count', models.BigIntegerField(blank=True, default=0)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('big_metadata', models.JSONField(blank=True, null=True)),
                ('secret_value', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.author')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.tag')),
            ],
        ),
    ]
